### ISSUE TITLE
Text layer doesn't resize with document

### ISSUE THREAD

**Issue by colesimmons** [wojtekmaj/react-pdf#110]
First of all, fantastic work on this. This is a huge answer to my prayers. 🙏 

One thing I noticed with my own experiments and the [demo](http://projekty.wojtekmaj.pl/react-pdf) as well is that, while the document is resizeable (in the demo - starting at original document size and shrinking as the browser window gets smaller), the text layer retains its starting position.

The implication for now is that I have to retain the scale that it is originally rendered with.

Is there a way to dynamically resize both the page and the text layer at the same time?

**Comment by wojtekmaj** [comment]
Hey @colesimmons!
My demo uses very simplified approach. You should always ensure you're rendering PDFs in their target size. Otherwise you could face multiple sizing/positioning issues, as well as performance degradation.
My demo, if done right, should actually listen for window resize and pass this parameter to React-PDF to allow it to rerender.

**Comment by colesimmons** [comment]
The demo rerenders the document correctly, but does not rerender the text layer to match.

To make sure we're on the same page, I'm talking about the demo at http://projekty.wojtekmaj.pl/react-pdf.

**Comment by wojtekmaj** [comment]
That's exactly what I meant. "My demo, if done right" - I implied it's not really done right in that manner :D

**Comment by colesimmons** [comment]
Ah okay 😃 

Thanks Wojciech!
