### ISSUE TITLE
Unable to require Document 

### ISSUE THREAD

**Issue by shardool-freightwalla** [wojtekmaj/react-pdf#118]
I am trying to incorporate react-pdf into my project and facing some starting hurdles.
The requiring of the package doesn't seem to work for me.
I am using ES5 and react: 15.6.2

Trying to require the package as below:
```
var Document = require('react-pdf').Document;
```
While using react-pdf v2.4.2, not able to import the variable
and while using react-pdf v1.6.1, Document variable is null

**Comment by wojtekmaj** [comment]
Hmmm... That is odd. What are you getting when running

```
var reactpdf = require('react-pdf');
console.log(reactpdf);
```
?

**Comment by shardool-freightwalla** [comment]
It prints ``` [object Object] ```
Hope this helps.

![screen shot 2017-12-15 at 11 13 43 pm](https://user-images.githubusercontent.com/17472264/34053741-fd8dcd16-e1ed-11e7-840a-ae115c4f3dc1.png)


Thanks for your time.

**Comment by wojtekmaj** [comment]
I think you're still importing a very old version of React-PDF :)

**Comment by shardool-freightwalla** [comment]
Yes, because I am unable to use the latest (v2.4.2) as it fails with ```Error: Unexpected token: In:``` due to the require statement mentioned above.
In my gulp script, I am just using browserify (and not babel), could that be a source of error.

I am unable to debug it more and provide any other details. Let me know what can help ?

**Comment by wojtekmaj** [comment]
Ah, yeah. 1.x is not compatible with 2.x at all, so you can't just use 2.x README. React-PDF 1.x was just 1 component capable of displaying 1 page. React-PDF went a long, long way since that time.

So your real problem is that you get this error, `Error: Unexpected token: In:`!
I'll try my best to help. I don't think that's a full error though. Do you have a stack trace? A screenshot of expanded error message in the console could do.
