### ISSUE TITLE
React PDF render slowly when processing large PDF 

### ISSUE THREAD

**Issue by sachinda123** [wojtekmaj/react-pdf#1319]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I used with latest package .   normally it work fine with out any delay . But when i generate around 300  pages  it take around 4 minute to process the pdf (After process pdf will size 300 MB ) . If there any specific method to improve performance  
`  <PDFDownloadLink
              document={
                <PDFReport
                  key={report.id}
                  report={report}
                  account={account}
                  user={user}
                  isFullPageImage={toggle}
                  includeImages={includeImages}
                  I18n={I18n}
                />
              }
              fileName={`${report.name}.pdf`}
            >
              {({ blob, url, loading, error, onLoadError }) => {
                console.log('onLoadError', onLoadError)

                return loading ? (
                  <SpinnerDiv>
                    <Spinner />
                  </SpinnerDiv>
                ) : (
                  <LinkContainer>
                    <PdfIcons src={pdf} />
                    <p style={{ fontSize: '2rem', fontWeight: 600 }}>
                      {I18n.t('report_download_pdf_button')}
                    </p>
                  </LinkContainer>
                )
              }}
            </PDFDownloadLink>`

### Steps to reproduce

generate large pdf

### Expected behavior

PDF Load Fater 

### Actual behavior

PDF Load Slowly

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by SaroGFX** [comment]
We are using a virtual scroll library like [Virtuoso](https://virtuoso.dev), which basically only renders te page when it's in view. 

It brings it's own challenges in terms styling, so I am keen to learn about other option too.

**Comment by danieljcksn** [comment]
I was trying to generate large documents—around 300 pages (not super dense, but still… three hundred pages). I first tried a handful of approaches, including Web Workers and other optimizations, but the render kept failing with errors like “Invalid array length.” The root cause was pushing all items into a single <Page>, which overloaded the layout pipeline and blew past internal array limits.
The fix was to render in chunks: split the dataset into slices of roughly 20 items and render each slice inside its own <Page>. 

This paging strategy keeps memory usage predictable, reduces layout complexity per pass, and avoids oversized arrays, so the document becomes stable and renders end-to-end. Functionally nothing changes for the reader—they still get one coherent PDF—but under the hood each page is built from a manageable slice of data, which is why it works. (And, for what it’s worth, they recommend not generating PDFs with more than ~25 pages anyway… :c)
