### ISSUE TITLE
Use react-zoom-pan-pinch blur pdf

### ISSUE THREAD

**Issue by huybuivan97** [wojtekmaj/react-pdf#1343]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

When zoom pdf use react-zoom-pan-pinch image blur

### Proposed solution

a

### Alternatives

a

### Additional information

a

**Comment by abartolo** [comment]
@huybuivan97 I am having the same issue. Any luck on resolving this?

**Comment by wojtekmaj** [comment]
PDFs are rendered at the exact size: described in PDF itself or defined using width/height or scale props. So, as you enlarge the rendered image, you'll have to render it again at a new larger size by updating said props. Or, render it larger than necessary at the beginning, if you're not worried about performance too much.

**Comment by sjonchhe** [comment]
is there any workaround to implement zoom with blur??

**Comment by matteo95g** [comment]
I'm seeing the same issue. Since `renderMode='svg'` won't be supported in the future, I'm using `renderMode='canvas'`. So when zooming using a pinch-to-zoom approach, the document looks blurry. I tried changing the scale of the document after zooming using pinch-to-zoom, but that made the document to be uncentered and the scroll seems to work badly after changing the scale. Not sure what could be the solution for it. Any workaround would be really helpful.

**Comment by tarikt-hybird** [comment]
bump

**Comment by adamkui** [comment]
Same issue here. I resolved this, by increasing the devicePixelRatio on zooming. More specifically, I multiply the scale from `react-zoom-pan-pinch` with `window.devicePixelRatio`. This seems to resolve the issue for all browsers, except for Safari.

**Comment by tarbence1** [comment]
@adamkui Have you found a solution to the safari problem? I have the same problem. devicePixelRatio is not supported in safari and on phone the pdf becomes blurry when zoomed.
