### ISSUE TITLE
React-pdf 7 causes " exceeds the maximum size limit of 50mb" build error on Vercel

### ISSUE THREAD

**Issue by w3bdesign** [wojtekmaj/react-pdf#1504]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

After trying to upgrade to React-pdf version 7 I am getting build errors on Vercel. 

`Error: The Serverless Function "_next/data/RGgqgLBLLHa65oFs5xGa9/nb-NO/cv.json" is 59.02mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
NOW_SANDBOX_WORKER_MAX_LAMBDA_SIZE: The Serverless Function "_next/data/RGgqgLBLLHa65oFs5xGa9/nb-NO/cv.json" is 59.02mb which exceeds the maximum size limit of 50mb.`

The PDF renders fine locally in `npm run dev` 

Downgrading to version 6 fixes the error

### Steps to reproduce

1. Clone https://github.com/w3bdesign/dfweb-v3 (or just use the CV page and component with the PDF)
2. Upgrade to version 7
3. Deploy on Vercel

### Expected behavior

I expect no build errors

### Actual behavior

Error: The Serverless Function "_next/data/RGgqgLBLLHa65oFs5xGa9/nb-NO/cv.json" is 59.02mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
NOW_SANDBOX_WORKER_MAX_LAMBDA_SIZE: The Serverless Function "_next/data/RGgqgLBLLHa65oFs5xGa9/nb-NO/cv.json" is 59.02mb which exceeds the maximum size limit of 50mb.

### Additional information

![image](https://github.com/wojtekmaj/react-pdf/assets/45217974/66abe94a-fe3e-4ba6-92c4-7b8930692fba)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 7.0.1
- **React version**: Next.js 13.3
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Huh. Built your repo locally with React-PDF 7, and got cv.json of 269 B.

**Comment by w3bdesign** [comment]
Yes, it is likely a Vercel issue, but something causes it to become very large.

**Comment by theAJFM** [comment]
Got this one as well, and I think it's caused by `canvas` getting included as a dependency in `pdf.js` starting from v3.0.279. Here's a conversation about this: https://github.com/wojtekmaj/react-pdf/issues/1504

**Comment by w3bdesign** [comment]
Can confirm this works

**Comment by theAJFM** [comment]
Next.js's `dynamic` does work in overcoming the vercel size limit during tracing, but it doesn't prevent the bundler from adding `canvas`'s extra 40MB to the bundle size. Maybe a bit of a nit at this point since you can't really avoid this if you really need to load the PDF server-side, but it's certainly not nothing.

**Comment by MattyBalaam** [comment]
I found a workaround to stop installing canvas if that might help? We add a new entry to the resolutions object in package.json for `canvas`:

https://github.com/mozilla/pdf.js/issues/16463

**Comment by jakepgoldman** [comment]
Any update on how to get around this?

**Comment by rodumani** [comment]
@jakepgoldman

I leveraged the same problem by adding resolutions in `package.json`.

```json5
{
  // Add the following config in package.json
  "resolutions": {
    "react-pdf/**/canvas": "link:./node_modules/.cache/null",
    "pdfjs-dist/canvas": "link:./node_modules/.cache/null"
  }
}
```

The above config makes it not to install the large canvas package in Vercel serverless deployment. 

Wish it can help you too.

**Comment by w3bdesign** [comment]
I am currently using this as a workaround:

```javascript
const PdfViewer = dynamic(() => import("./PDFViewer.component"), {
  ssr: false
});
```

**Comment by juchiast** [comment]
https://github.com/wojtekmaj/react-pdf/issues/1504#issuecomment-1697124381

**Comment by criskell** [comment]
any new?

**Comment by raimille1** [comment]
For us the resolutions route did not work since we're workign with pnpm and package the app differently. When you look at the original issue here, it is that canvas is being packaged on server side code when for most cases here people are loading it dynamically on the client side. To avoid it being packaged, we added an experimental setting on our next.config.js file `outputFileTracingExcludes`. For all routes `*`, do not package 'node_modules/.pnpm/canvas@*`.

For our case specifically we're using pnpm, but your node_modules path to canvas will look differently, just check the output logs for your build and you'll see the tracing outputs that are large. You can safely exclude them here if you're only using them on the client side.

```
  experimental: {
    outputFileTracingExcludes: {
      // Avoids including canvas in the trace to avoid 50 Mb+ serverless functions
      '*': ['node_modules/.pnpm/canvas@*']
    }
  },
```
