### ISSUE TITLE
React-pdf v7 is more sensitive to rerenders than v6

### ISSUE THREAD

**Issue by MattL75** [wojtekmaj/react-pdf#1526]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Our app was working fine in v6. After migrating to v7, we started seeing many bugs. In some cases, **infinite loops** of loading workers and documents. We have a fairly complex and convoluted setup (legacy app) so I am having a very hard time reproducing. The errors we see after a little bit are the ones in the below tickets, but I don't think the tickets are related. The info seems very different.

Related issues: https://github.com/wojtekmaj/react-pdf/issues/974 https://github.com/wojtekmaj/react-pdf/issues/1062

**Here's the kicker. If I replace the Document.tsx component with the Document.jsx component from v6, everything works fine.**

I'm assuming that turning the components to hooks made them more sensitive. In particular, I'm theorizing that it's related to https://github.com/wojtekmaj/react-pdf/blob/v6.2.2/src/Document.jsx#L78 as with the hook implementation there is really nothing preventing a rerender of the same file if you end up in a weird async state (which we are).

Just opened the ticket to maybe get some opinions and have a place for others to maybe share some ideas.

### Steps to reproduce

Currently working on it. Been trying to hack together a repro for a few days and no luck. 

### Expected behavior

No infinite loops

### Actual behavior

Infinite loops

### Additional information

@wojtekmaj I don't have a repro yet. I can just tell you that replacing the v7 Document.tsx with the Document.jsx implementation in v6 fixes the problem. 

I thought I'd still create a ticket to pool other people having the issue, if any.

### Environment

- **Browser (if applicable)**: chrome
- **React-PDF version**: 7+
- **React version**: 18
- **Webpack version (if applicable)**: 5.76.0

**Comment by vsolominov** [comment]
Ran into a similar problem when upgrading react-pdf from version **6.2.2** to version **7+**. I use [react-virtuoso](https://github.com/petyosi/react-virtuoso) to work with large multi-page documents. On version **6.2.2**, I did not notice any problems. After updating to **7.1.0**, I began to observe problems when scrolling (especially if you scroll quickly up). I suspect that this is due to the constant re-rendering of pages. Wrote a simple [example](https://codesandbox.io/s/react-pdf-react-virtuoso-7fq5jr) to illustrate the problem.

**Comment by wojtekmaj** [comment]
Check out 7.1.1. Might be a bit better.

**Comment by wojtekmaj** [comment]
StrictMode? :) loadDocument is an effect.

**Comment by MattL75** [comment]
Our app doesn't run in strict mode :L

**Comment by Evanc123** [comment]
I've also had to roll back to 6.2.2, v7 the text layer causes rendering issues. will post more details in a bit

**Comment by wojtekmaj** [comment]
Does any of the participants have any updates/findings/breaking examples to share? If not, I'll be closing this in a bit.

**Comment by vstollen** [comment]
I'm not sure if this is related, but I am getting the error `this.messageHandler is null` in my implementation. The error does not occur when I downgrade to 6.2.2.

Interestingly, the error only seems to happen when I pass `options` to `<Document>`.

I have added a minimal reproduction here: https://codesandbox.io/s/react-pdf-7-3-3-errors-t3mfc2

In our actual implementation, we debounce the resize events and have a little more logic involved, which I have excluded for simplicity.

**Comment by wojtekmaj** [comment]
@vstollen This has to do with the way you've defined options. Documentation suggests doing so outside of React function and for a good reason. Once I did this, the error was gone.

**Comment by vstollen** [comment]
@wojtekmaj thanks for the prompt response!

I do not want to pollute this issue with unrelated problems, but would it be possible to have a dynamic options object?

Specifically, I want to add an `Authorization` header in my `options` object, where the token is a reactive value that changes occasionally.

**Comment by vsolominov** [comment]
> Does any of the participants have any updates/findings/breaking examples to share? If not, I'll be closing this in a bit.

I am trying to solve a virtualisation problem for continious scrolling. The [recipe given on the Wiki](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages) is not optimal.

Tried to use `react-window` as a third party library. Found your example [react-pdf-react-window-fullscreen](https://codesandbox.io/s/react-pdf-react-window-fullscreen-ky4yy0). However, page rendering is quite slow with this library.

On earlier versions of `reac-pdf` I used the `react-virtuoso` library, which had good performance. However, since versions 7+, page rendering is "chaotic" and "flies off into space" with a little scrolling. Sample code:
```ts
const pageCount = 14;
const pageHeight = 700;
const rootElement = document.getElementById("app");

createRoot(rootElement).render(
  <StrictMode>
    <Document key={"Test.pdf"} file={samplePDF}>
      <Virtuoso
        style={{ height: `${pageHeight}px` }}
        totalCount={pageCount}
        defaultItemHeight={pageHeight}
        itemContent={(index) => <Page pageIndex={index} height={pageHeight} />}
      />
    </Document>
  </StrictMode>
);
```
![example](https://github.com/wojtekmaj/react-pdf/assets/116663980/8a578857-0226-4698-abe4-753c5dcb891f)

**Comment by MattL75** [comment]
Forgot to report back here. Fixed this a while back. Our app had dynamic options property. Took quite a bit of refactoring but we managed to remove that need. Still not sure why it was working in v6 but not in v7. Anyways, for anybody having this issue, just define static options either outside the react component or in a useMemo. 

I see a lot of unrelated issues in this thread. If you have an issue different from this one please make a new ticket with your own circumstances so it can be tracked better. For now I will close this one.

**Comment by jovana** [comment]
> Use useMemo to prevent recreating options object with every render.

Do you have an example how to use the useMemo for the <Page />. I have the issue it keeps looping.
Using this code it works, and gives me one page:
```
<Page pageNumber={1} />
```

Using this code, this page kept rerendering:
```
 <Document file={file} onLoadSuccess={onDocumentLoadSuccess} options={options}>
            {Array.from(new Array(numPages), (el, index) => (
              <Page
                key={`page_${index + 1}`}
                pageNumber={index + 1}
                width={containerWidth ? Math.min(containerWidth, maxWidth) : maxWidth}
              />
            ))}
          </Document>
``` (this code snipped is from the example page: https://github.com/wojtekmaj/react-pdf/blob/0cbb75af635affdb1c0a8027c94e3fda509f0291/sample/create-react-app-5/src/Sample.tsx#L66) This problem seems in the versions 7.1.1 and 7.4 and 7.6.

Thanks for helping me out!!

**Comment by grundmanise** [comment]
We managed to resolve these issues by memoizing non-primitive props using useMemo, useRef, or useCallback. Hope this helps someone
