### ISSUE TITLE
react-pdf not effect in 钉钉browser 

### ISSUE THREAD

**Issue by day-xue** [wojtekmaj/react-pdf#1680]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

 Dingtalk browser does not support fetch api, resulting in an error ，(undefined is not an object evaluating body.getReader), what should i do

### Steps to reproduce

1.download 钉钉 browser
2.use react-pdf to preview a pdf

### Expected behavior

dont use  fetch.  

### Actual behavior

use fetch

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
This browser is not listed as supported browser in README, so I'm going to close this ticket because it cannot be considered a bug we're not delivering something we didn't promise in the first place. Still, if you have an idea how to improve compatibility without too many changes for other browsers, feel free to contribute.
