### ISSUE TITLE
Can I handle PDF.js worker myself instead of using Webpack?

### ISSUE THREAD

**Issue by sallyhill** [wojtekmaj/react-pdf#252]
**Before you start - checklist**
 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I'd like to be able to disable the separate loading of pdf.worker.js through webpack. Our webpack is not cooperating and we've been troubleshooting for a few days. We have a separate asset pipeline for local webpack builds vs prod webpack builds because we are serving our front end through a ruby backend.

**Describe solutions you've tried**
We cannot get consistent behaviour locally vs when we deploy using react-pdf. Locally, we get a CORS error but it tries to load the right s3 file. When we deploy, we see that it tries to fetch the page url as a javascript file instead of the s3 url. I'm wondering if we could get more consistent behaviour if `react-pdf` concerned itself less with our front end build. - aka if we could just opt out of the service worker help since it's the only thing on the page at that time that needs to be loaded in our case anyway.

**Additional information**
Add any other context or screenshots here.

**Environment**
 - Browser [e.g. Chrome 57, Firefox 59]: Version 67.0.3396.99 (Official Build) (64-bit)
 - React-PDF version [e.g 3.0.4]: react-pdf@^3.0.5

**Comment by wojtekmaj** [comment]
Hi there,

Yes, it's totally possible. entry.webpack is an entry file you can use to get it running quickly. You can also use CopyWebpackPlugin or other solution to copy pdf.worker.js to your dist folder, and use default entry file (`import { ... } from 'react-pdf'`).

The issue you're having is unlikely to be resolved by this (although might help with build speed). I think the issue here is more of a Webpack/Browser one. Here's what I think:

* CORS is expected when you load a file from another domain. So naturally you will be able to load the file from s3 on a website that sits on s3 domain, but you will not be able to do so on a website that sits on your localhost.
* Regarding "it tries to fetch the page url as a javascript file". Could you elaborate? Is Webpack getting its bundles (in this case: bundle with the worker) from a wrong location? Do you have the code of your app split into several bundles? Are they loading properly? You are likely missing something from your Webpack config (it might not work without some changes to Webpack config if you e.g. upload your code in `http://example.com/someDirectory/`).

**Comment by sallyhill** [comment]
Hello, You were right, it was an issue with us needing to declare our webpack output properly in production!
I read about the 1.js file that pops up as part of pdf.js output with webpack and then didn't feel that that behaviour was as strange.
