### ISSUE TITLE
Text layer is misaligned when when overflow scroll is set on container

### ISSUE THREAD

**Issue by hoffmannjan** [wojtekmaj/react-pdf#259]
Hi,

I've got one issue with `react-pdf` when I'm trying to render `<Page>` with set `scale` inside container with set `overflow: scroll`.

The effect is that:

<img width="690" alt="screenshot 2018-08-25 16 07 50" src="https://user-images.githubusercontent.com/3756160/44619680-f853e100-a88a-11e8-8f8c-76c4a247d1d0.png">

```
<div className="w-80 vh-85 overflow-scroll bg-near-white">
  <Document file={file} onLoadSuccess={this.onDocumentSuccess}>
    <Page
      pageNumber={pageNumber}
      renderTextLayer={true}
      scale={this.state.scale}
      customTextRenderer={textItem => {
        if (searchFromUrl) {
          return textItem.str
            .toLowerCase()
            .split(searchFromUrl)
            .reduce(
              (strArray, currentValue, currentIndex) =>
                currentIndex === 0
                  ? [...strArray, currentValue]
                  : [
                      ...strArray,
                      // eslint-disable-next-line react/no-array-index-key
                      <mark key={currentIndex}>{searchFromUrl}</mark>,
                      currentValue
                    ],
              []
            );
        } else {
          return textItem.str;
        }
      }}
    />
  </Document>
</div>
```

When I remove `w-80 vh-85 overflow-scroll` wich is 
```width: 80%;
max-width: 80%
height: 85vh; 
overflow: scroll;
```
everything renders correctly.

Is there any workaround to pass to `Page` real width and have It render properly or do I need to fork library ?

Best, JH

**Comment by wojtekmaj** [comment]
You can absolutely pass `width` prop to `Page`, as stated in documentation. Starting with `v4.0.0` you can also use `height` which would probably be more interesting to you as I see.

If you manipulate the layout so that the PDF does not fit on the page, you will probably need to do more CSS work to keep stuff aligned.

**Comment by N1kto** [comment]
@wojtekmaj 
I have had a similar problem (misaligned text layer) when document is zoomed in. Overriding `.react-pdf__Page__textContent` styles
from 
```
top: 50%;
left:  50%;
transform: translate(-50%, -50%) rotate(${rotate}deg);

```
to:
```
top: 0;
left: 0;
transform: none;

```
fixed the issue: text is always aligned properly. 

However, theses styles were there for some reason, which is not clear for me. Not clear because `top` and `left` (`50%`) values were compensated with corresponding translates in `transform` rule (`-50%`).

I understand setting `transform: none` breaks rotation adjustment, but is there anything else (related to positioning) that can be broken because of that?

Kind thanks in advance.

**Comment by wojtekmaj** [comment]
Hmmm, I styled that a while ago and I have no idea why I didn't just write

```
  top: 0;
  left: 0;
  transform: rotate(${rotate}deg);
```

🤔 

Maybe it has to do something with this rotation, that layers were misaligned when rotated...
