### ISSUE TITLE
SVG rendering displays odd unicode characters instead of letters

### ISSUE THREAD

**Issue by taherbert** [wojtekmaj/react-pdf#309]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

Prior to the 4.0 update, SVG rendering used the PDF's actual text content. Now, there appear to be odd unicode characters for each character. I saw your discussion on this issue [here](https://github.com/mozilla/pdf.js/issues/10205), but didn't see a resolution.

I was using these characters to perform searching + highlighting with SVG Rects, but am unable to do so now. I have tried using canvas with a text layer, but the text inside of `mark` tags is always the wrong typeface and misaligned.

Do you have any suggestions on how to convert the unicode characters to actual letters?

**Comment by wojtekmaj** [comment]
Hi,
this is expected result of Mozilla's change. I don't like their change too, since this forced me to render a TextLayer over a perfectly fine SVG text, so I reported mozilla/pdf.js#10205 you have mentioned and we're tracking it there.

Since neither I nor you can do anything about it, I am going to close this issue, but I *will* reopen it in case Mozilla would enable me to bring back the old behavior.

Thanks for reporting!
