### ISSUE TITLE
Duplicate code in main webpack bundle and "pdfjsWorker"

### ISSUE THREAD

**Issue by rogordan** [wojtekmaj/react-pdf#340]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Correct configuration of worker in webpack with minimum code duplication.

**Describe solutions you've tried**

I've tried using entry.webpack and regular entry file. In the former case, two files with hash names are produced by webpack that appear to both be copies of pdf.worker.js. In both cases a separate chunk is produced automatically called pdfjsWorker. Diffing this chunk with the main chunk shows that there is a huge amount of pdfjs code shared between the two. Nevertheless, pdfs aren't rendered successfully without the pdfjsWorker chunk.

So my questions is: How do I create a single pdfjs worker and not duplicate any code between chunks?

**Additional Information**

I am using splitChunks. I think this automatically splits out a new chunk based on this line in entry.webpack:
`import PdfjsWorker from 'worker-loader!./pdf.worker.entry.js';`
But I can't find what might cause similar behavior when an entry file is not specified.

Currently my web page (no entry.webpack, no copy of [hash].worker.js) renders pdfs without becoming uninteractive. Does this mean I am using a worker supplied by pdfjsWorker somehow?

**Environment**

 - React-PDF version 4.0.2:
 - React version 16.7.0:
 - Webpack version (if applicable) 4.29.0:

**Comment by wojtekmaj** [comment]
Hi,
this is expected. I believe the way it works is that if your browser supports Workers, then pdf.worker.js will kick in. But if not, PDF.js will fall back to a "fake" worker, with identical functionality, but working on the same JavaScript thread. The code is almost entirely identical, with the exception of one code being wrapped in a Worker and the other not.

I realize this is less than ideal, but in real life you should not see both versions downloaded, so your users will either use one or another.

Worker will always be created as a separate chunk, because it being Worker has to be a separate file, regardless of splitChunks enabled or not.
