### ISSUE TITLE
How to pass styles to `Page` component? I need a smoothy transition when scaling!

### ISSUE THREAD

**Issue by ClementeSerrano** [wojtekmaj/react-pdf#411]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I would like that when scaling the `Page` component, the scale transition is smooth (in `css` by adding: `transition: transform .3s`).

**Describe solutions you've tried**

Adding `style={{transition: "transform .3s"}}` prop to `Document`, `Page` and any container of them

**Additional information**

**Environment**

 - Browser (if applicable): Chrome Version 74.0.3729.169
 - React-PDF version : `4.0.5`
 - React version: `16.7.0`
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by PupoSDC** [comment]
The problem seems to be that every time the page scale changes, the id passed to the component is forcebly changed. See [this line of code](https://github.com/wojtekmaj/react-pdf/blob/9854baeb68aedf192a0f93154a4daf9d05a2ec8f/src/Page.jsx#L239).

Is there a reason why this is necessary? I too would like to animate scale transitions and it's currently not possible.

**Comment by moshfeu** [comment]
I need that too. It's not only impossible but every scale change seems like re-rendering the page so it blinks

**Comment by moshfeu** [comment]
@wojtekmaj any chance to consider allowing smooth transition on scale?
