### ISSUE TITLE
Retrieve page number of a highlighted text

### ISSUE THREAD

**Issue by Gopes396** [wojtekmaj/react-pdf#484]
@wojtekmaj, I have used your example to highlight a searched text. How do we get the page number of the found string?

**Comment by wojtekmaj** [comment]
`customTextRenderer` gets all the data a TextLayerItem gets, so

```js
{
  customTextRenderer: PropTypes.func,
  fontName: PropTypes.string.isRequired,
  itemIndex: PropTypes.number.isRequired, // eslint-disable-line react/no-unused-prop-types
  page: isPage.isRequired,
  rotate: isRotate,
  scale: PropTypes.number,
  str: PropTypes.string.isRequired,
  transform: PropTypes.arrayOf(PropTypes.number).isRequired,
  width: PropTypes.number.isRequired,
}
```

So, you have access to `page` and thus its properties, `pageIndex`, `pageNumber`.

**Comment by Gopes396** [comment]
I would like to rephrase my question. My requirement is to navigate to the page the text is highlighted. Is there a way to programmatically do this? How does CustomTextRenderer highlight words in all pages? Does it have pageNum as it's parameter?

**Comment by wojtekmaj** [comment]
To highlight the text, you need to render it first. If the page is not rendered yet, you won't be able to use customTextRenderer.

However, if the page is rendered:

customTextRenderer allows you to replace the default text rendering technique in TextLayerItem (being: rendering plain text), and thus allowing you to add a highlight.

Since you can add any React component to highlight the text (like `mark`), you can also attach `ref` to get DOM element and navigate to it using `element.scrollIntoView()`.

**Comment by gabrielo91** [comment]
Hello @wojtekmaj , I'm facing the exact same issue as ghost, the problem is that I have rendered the pdf one page a time, and we have a navigator to move through them, as you can see in the below image:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/17114924/193166285-8378cbe9-eefd-41b8-a57c-b3741d5f00cc.png">

We need to implement a functionality in order to take the user through the pages stepping over all the highlighted  words, that's why we would like to know if there is a way to get the page number where every item was rendered.

Thanks in advance!

**Comment by JeromeGill** [comment]
@gabrielo91 did you ever solve this? I have the same use case and it really isn't obvious
