### ISSUE TITLE
The text-rendering is offset, creating graphical problems.

### ISSUE THREAD

**Issue by kevin-fang** [wojtekmaj/react-pdf#64]
When I render a PDF containing just text, the text seems to be rendered separately from the canvas.

![react-pdf-text-render-off](https://user-images.githubusercontent.com/9577819/30677979-10421554-9e5d-11e7-9f31-b855a8abd5c3.PNG)

**Comment by wojtekmaj** [comment]
Hello,
if you have a feeling that text is rendered separately, that's because it is.
You need to be careful not to break the styles. Also be sure to render the page in such a way that it won't get shrunk by things like max-width - max-width will work on canvas, but not on the text, obviously.
If you have your example online somewhere I could try to help, or you could look at [my simplest example](http://projekty.wojtekmaj.pl/react-pdf/) which I believe is working correctly.
