### ISSUE TITLE
How to detect external link click

### ISSUE THREAD

**Issue by shiraji** [wojtekmaj/react-pdf#661]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I would like to detect which external link in PDF file is clicked for logging.

**Describe solutions you've tried**

* Read document
* Read html code (yes, the link was generated as A tag and it is clickable.)
* Try onItemClick but it only gives me page number

**Additional information**

None

**Environment**

 - React-PDF version [e.g. 3.0.4]: 5.0.0
 - React version [e.g. 16.3.0]: 16.13.1

**Comment by wojtekmaj** [comment]
If you click an _internal_ link, onItemClick function in Document is going to be called with `{ pageNumber }` as an argument. Indeed, there are no more interesting properties I can given to the developer here.

If you click an _external_ link, then React-PDF should not fire onItemClick. It should just allow you to click the external link, that's it. If you would like to detect it, then proceed as if you had plain `<a>` link (because that's exactly the case) and use, perhaps, event bubbling to check if a link inside PDF has been clicked.

**Comment by ming2024** [comment]
@wojtekmaj is it possible to make the link open external window?
