### ISSUE TITLE
Failed to load PDF file from an array

### ISSUE THREAD

**Issue by Hisashin7331** [wojtekmaj/react-pdf#698]
So I got the array I'll simplify to
```
import pdfOne from 'pdfOne.pdf'
import pdfTwo from pdfTwo.pdf'
export const array = [{id: 1, doc: pdfOne}, {id: 2, doc: pdfTwo,}];
```
and I'm rendering `<Document>` using  

```
import { Document } from 'react-pdf';
import array from 'array'
array.map((item) => {
   return (
      <Document file={item.doc} key={item.id} />
   );
});
```
and I get alternating between 'Failed to load PDF file' with 'Loading PDF file' and displaying nothing.
I tried using url rendering with
```<Document file={{ url: `/${item.doc}` }} key={item.id} />```
but it gave me just 'Failed to load PDF file' with worker error in console
```const pdfOne = require('pdfOne.pdf');``` renders infinite PDF Loading

 - Browser Chrome: 87.0.4280.88:
 - React-PDF version: 16.4.8:
 - React version: 17.0.1:
 - Webpack version: 4.44.2:

**Comment by wojtekmaj** [comment]
Tried to reproduce your issue but I'm not able to. Can you try and reproduce that on CodeSandbox?

If you fail to do so, chances are the issue is with your configuration and how you load PDF files in your Webpack.

If you cannot do this, try and check `onSourceError`, `onLoadError` callback props on `<Document />`, which may tell you more about the issue you're facing.
