### ISSUE TITLE
Multiple PDFs on a page

### ISSUE THREAD

**Issue by sleblang** [wojtekmaj/react-pdf#715]
Hello, 
Is there documentation showing how to load multiple PDFs on a page? Would like to have the ability to show a number of PDFs on a page, i.e, rows / cols - showing initial first page would be fine as don't need to show the all the pages.

Thanks.

**Comment by wojtekmaj** [comment]
Sure, why not? Just use as many `<Document />` components as you like.

**Comment by OrlandoMaya** [comment]
I did just this, but sometimes I don't know if it's because of the fetch load, or some worker problem that makes the documents load backwards for example:

I have 2 documents or PDFs in an array and I make a map to display them ([sample1 and sample2]). 

Sometimes it happens that it tries to render first the sample2 and then the sample1, but the component renders the sample1 with the pages of the sample2.

Do you know what would be the correct way to render multiple PDFs?
