### ISSUE TITLE
How to get text content overlapping with annotation?

### ISSUE THREAD

**Issue by jvhoffbauer** [wojtekmaj/react-pdf#766]
Is it possible to determine, which text is contained in an annotation, i.e. can I somehow determine, which <span> objects from text layer an annotation (box) overlaps with? If possible, can I also break it down to a character level, i.e which characters are in the annotation? 

If you could give any hints on this, that would be highly appreciated.

**Comment by wojtekmaj** [comment]
General JavaScript problem since we will have to work on rendered HTML but:

Get the annotation you want

```js
const annotation = …
```

Find text content layer

```js
const textContent = document.querySelector('.react-pdf__Page__textContent');
```

Build a function to check if two elements collide

```js
function isColliding(a, b) {
    var aRect = a.getBoundingClientRect();
    var bRect = b.getBoundingClientRect();

    return !(
        ((aRect.top + aRect.height) < (bRect.top)) ||
        (aRect.top > (bRect.top + bRect.height)) ||
        ((aRect.left + aRect.width) < bRect.left) ||
        (aRect.left > (bRect.left + bRect.width))
    );
}
```
[source](https://stackoverflow.com/a/35974082/1925425)

Find text content layer children that collide with annotation

```js
[...textContent.children].filter(b => isColliding(annotation, b));
```

Worked for me!

![Zrzut ekranu 2021-07-9 o 08 33 27](https://user-images.githubusercontent.com/5426427/125033988-57ed1600-e090-11eb-814a-06a1d601df7e.png)

You will have to work on isColliding function so that it gives you % of overlap or something because this function returns true even if they are barely touching, leading to what you may consider false positives.
