### ISSUE TITLE
Unimplemented widget field type "Sig", falling back to base field type.  Introduced through a CDN

### ISSUE THREAD

**Issue by zhangmingcheng0412** [wojtekmaj/react-pdf#772]
**Before you start - checklist**

 - [ ] I followed instructions in documentation written for my React-PDF version
 - [ ] I have checked if this bug is not already reported
 - [ ] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Short description of the bug you encountered.

**Steps to reproduce**

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

What you expected to happen?

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
See https://github.com/mozilla/pdf.js/issues/1076.
Support for signatures has been just merged: https://github.com/mozilla/pdf.js/pull/13214 so it will be available in React-PDF once Mozilla releases the next stable release & we update React-PDF to use it.

Since updating pdfjs-dist is a no-brainer for this repo I'm going to close this ticket because no additional action is necessary.

**Comment by Albert-ch** [comment]
I have the same problem. When will it be updated

**Comment by wojtekmaj** [comment]
Support for Sig type has been added in [v5.4.0-beta.2](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.4.0-beta.2).
