### ISSUE TITLE
Blurred and Low Resolution view

### ISSUE THREAD

**Issue by jackvik** [wojtekmaj/react-pdf#849]
Hi Team,
the pdf view is blurry and light coloured text which is hard to view. On zoom, it comes clear. but on android device , it's very blurred in normal view and unclear. Is there any styling or font or something we can apply to improve the view?

**Comment by wojtekmaj** [comment]
You can try different renderMode, or rendering using different resolution and scaling it back down using CSS 🤔 Can't tell anything else without repro repo

**Comment by jackvik** [comment]
Changing the renderMode not improving the text visibility. But zooming , it's clear. Can we change font size or font colour?

**Comment by jackvik** [comment]
Is there any option to change resolution?

**Comment by wojtekmaj** [comment]
You can set `scale={2}` for example, and scale it down using CSS. It's complicated but could do the trick.

Are you using a high res screen by any chance?

**Comment by jackvik** [comment]
I am using android studio to test the same.but on chrome browser of laptop, it's clear. but on mobile simulator or mobile device it isn't

**Comment by Anhaachan** [comment]
why this question closed? i just rendered it as `svg` . it works but when multiply page . it won't render all page.

**Comment by gfargo** [comment]
> why this question closed? i just rendered it as `svg` . it works but when multiply page . it won't render all page.

Rendering as `svg` has been deprecated in newer versions.  Not sure if this is a valid solution for folks using new version of the lib that only support `custom` or `canvas` 💭

**Comment by Thiago2104** [comment]
I also face the same problem with rendering PDFs using react-pdf. The resolution is quite noticeable, especially since I need to display a very large PDF. While scaling is a necessary approach, I've found that using react-pdf requires significantly more scaling to achieve readable text compared to embedding the PDF in an iframe, object tag, or similar methods, which require less zoom for the same level of readability.

I would appreciate any guidance on improving the resolution, or at least the possibility of implementing a custom renderer that behaves similarly to SVG.

**Comment by Sparkenstein** [comment]
![image](https://github.com/user-attachments/assets/bb51298f-73ad-4a03-ab60-e1c3bd279708)


Same here. scaling PDF is not the solution here, the rendering is broken here

**Comment by midhunweb** [comment]
any solution to this?
