### ISSUE TITLE
PDF content missing

### ISSUE THREAD

**Issue by selvaganapathy5995** [wojtekmaj/react-pdf#864]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**
   While loading the PDF some of the content missing.
   But while opening the PDF separately in adobe its showing everything.
   
**Expected behavior**
  The PDF should be load without any content missing.

What you expected to happen?
  In case if the content missing is their any exception handler that can catch this issue.

**Environment**

 - Browser (if applicable) [Chrome 94.0.4606.54]:
 - React-PDF version [3.0.5]:
 - React version [16.8.6]:

**Note: Could you guys please reply ASAP because it should be resolved with in a month.**

**Comment by jelizarovas** [comment]
Can you include comparison screenshots of what is missing?

**Comment by selvaganapathy5995** [comment]
![Expected image with full content](https://user-images.githubusercontent.com/91255025/135799604-f4377860-e97e-49d3-91f2-d323b422cbdd.png)
![Content missing pdf](https://user-images.githubusercontent.com/91255025/135799607-f8cc8201-ebaa-44a4-9cd5-d1f72c80ad6f.png)
@jelizarovas Thanks, FYI above are the image of the pdf one with content properly displayed another one with the content missing.

**Comment by jelizarovas** [comment]
Could it be a read only form fields and maybe not importing annotation layer?

Try

Support for annotations
If you want to use annotations (e.g. links) in PDFs rendered by React-PDF, then you would need to include stylesheet necessary for annotations to be correctly displayed like so:
```
// using ES6 modules
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';

// using CommonJS modules
import 'react-pdf/dist/umd/Page/AnnotationLayer.css';
```

**Comment by nebalceroc** [comment]
> > I'm having the same issue. Mainly text goes white.
> 
> Does the text color turn white, but you can still select the text or is it completely missing?

Yes, text is there but its white.

**Comment by lhg81hc** [comment]
I had the same issue using React 16.9.0 and React-pdf 4.1.0 (on both FireFox and Chrome). Upgrade to 5.5.0v solved the problem

**Comment by selvaganapathy5995** [comment]
@lhg81hc please check and let me know whether it display the PDF  content with dimension of PDF above 60 inches width and 49 inches height if possible after OCR.

**Comment by xinumh** [comment]
![image](https://user-images.githubusercontent.com/74340705/140880406-54cc0289-b920-4a7a-af40-4565a7ee9deb.png)
same issue on Chrome 69.0.3497.100(32)

**Comment by lhg81hc** [comment]
Hi @selvaganapathy5995 , sorry but what do you mean by OCR. `PDF content with dimension of PDF above 60 inches width and 49 inches height` Are you asking about the content that didn't got render before or the whole PDF file? My issue only happens for some parts of the PDF file

**Comment by selvaganapathy5995** [comment]
Hi @lhg81hc thanks, There is an option to OCR the pdf (60 inches width and 49 inches height) in my app once if it OCR then the entire screen is blank.  Below I attached the OCRed pdf use it in the given link.
U can able to reproduce it.
[](https://projects.wojtekmaj.pl/react-pdf/test/)
[pumpkin_after_ocr.pdf](https://github.com/wojtekmaj/react-pdf/files/7511133/pumpkin_after_ocr.pdf)

**Comment by tarochipz** [comment]
Also seeing the same issue on Chrome 94.0.4606.54 (issue appears on Firefox as well, but not Safari).

I get the same error message as @archearth:
`Warning: getOperatorList - ignoring errors during "RenderPageRequest: page 0" task: "DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function at() { [native code] } could not be cloned.".`

Looking into this error message, I believe it is caused by specific content in the PDF. When data is transferred between workers via postMessage the "[structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)" is used to copy JS objects. [Certain things like functions ](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#things_that_dont_work_with_structured_clone) don't work with the structured clone algorithm. The pdfjs worker throwing the error above indicates that a message can't be cloned because there is a property in the message's data that's not supported by this algorithm.

The web worker I'm using is on pdfjs version 2.1.266 (from cdnjs.cloudflare.com/ajax/libs/pdf.js/2.1.266/pdf.worker.min.js), and using `react-pdf` version 4.1.0 (which uses pdfjs 2.1.266). According to [this issue in pdf.js](https://github.com/mozilla/pdf.js/issues/13870) 2.1.266 is no longer supported. According to this [other similar issue in pdf.js](https://github.com/mozilla/pdf.js/issues/13771#issuecomment-885777078), all versions before 2.5x of pdfjs will encounter the issue above if the standard Courier font is used (as opposed to embedded) in the PDF.  

I've tried updating react-pdf to the latest 5.x version but this causes other issues and I'm seeing inconsistent behavior across browsers. It looks like the latest 5.x version is not compatible with IE so we'll have to stick with the latest 4.x but the latest 4.x version of react-pdf ifsusing pdfjs 2.1.266 (latest 5.x is using pdfjs v. 2.9.359).  Can you share some insight into why react-pdf 5.x isn't compatible with IE?

**Comment by jwcheon** [comment]
@selvaganapathy5995  Did you get this missing text issue solved? Facing the same problem but can't fix it.

**Comment by archearth** [comment]
@jwcheon try updating pdf.worker.js to the latest version. That, I think fixed it for me.

https://cdnjs.com/libraries/pdf.js/2.16.105

**Comment by wojtekmaj** [comment]
You should never update PDF.js worker to a version not matching PDF.js used. Please import pdfjs from react-pdf to extract `version` from it, and build the URL this way, as stated in documentation.

**Comment by NikhilAgarwal05** [comment]
Did anyone find the solution to this issue of missing letters in pdf while viewing?

**Comment by jwcheon** [comment]
@NikhilAgarwal05 I wasn't able to find a clear solution and just ended up changing the font I was using for this. Please let me know if you run into a solution thanks :)

**Comment by wojtekmaj** [comment]
Make sure you're running at least v6.2.2. It was the one that shipped an important fix that solved rendering issues for most of the folks out there.
